- Java/SistemaEstudiantes/.gitignore
- Java/SistemaEstudiantes/.idea/.gitignore
- Java/SistemaEstudiantes/.idea/dataSources.xml
- Java/SistemaEstudiantes/.idea/encodings.xml
- Java/SistemaEstudiantes/.idea/misc.xml
- Java/SistemaEstudiantes/.idea/sqldialects.xml
- Java/SistemaEstudiantes/.idea/vcs.xml
- Java/SistemaEstudiantes/pom.xml
- Java/SistemaEstudiantes/src/main/java/UTN/Main.java
- Java/SistemaEstudiantes/src/main/java/UTN/conexion/Conexion.java
- Java/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java
- Java/SistemaEstudiantes/src/main/java/UTN/dominio/Estudiante.java
Terminamos con el proyecto pendiente del semestre pasado. Video 1 y 2: Método eliminar estudiante y test
Se copia todo el proyecto a la carpeta del cuarto semestre.
> #6 (Java / Metodología) 4to Semestre

- Python/Tecnicatura3Py/Leccion07/laboratorio_usuarios.uxf
Videos 1.0 a 1.2
Se realiza diagrama uxf en UMLET
Y se crea la base de datos localmente
> Python - Laboratorio Clase 1

- Python/Tecnicatura3Py/Leccion07/capa_datos_persona/.idea/.name
- Python/Tecnicatura3Py/Leccion07/capa_datos_persona/.idea/vcs.xml
- Python/Tecnicatura3Py/Leccion07/capa_datos_persona/.idea/workspace.xml
- Python/Tecnicatura3Py/Leccion07/capa_datos_persona/menu_app_usuario.py
- Python/Tecnicatura3Py/Leccion07/capa_datos_persona/usuario_dao.py
> Python - laboratorio (1.5-1.6)

- Java/SistemaEstudiantes/src/main/java/UTN/presentacion/SistemaEstudiantesApp.java
> Java - metodologia (5-6)

- JavaScript/e-commerce2022/client/js/index.js
- JavaScript/e-commerce2022/client/js/products.js
> JavaScript - Laboratorio(video 3)

- Python/ProyectosPython/.idea/.gitignore
- Python/ProyectosPython/.idea/ProyectosPython.iml
- Python/ProyectosPython/.idea/inspectionProfiles/profiles_settings.xml
- Python/ProyectosPython/.idea/misc.xml
- Python/ProyectosPython/.idea/modules.xml
- Python/ProyectosPython/.idea/vcs.xml
- Python/ProyectosPython/Clase01/.idea/inspectionProfiles/profiles_settings.xml
- Python/ProyectosPython/Clase01/.idea/vcs.xml
- Python/ProyectosPython/Clase01/.idea/workspace.xml
- Python/ProyectosPython/Clase01/valores_infinitos.py
> Laboratorio 4

- Java/estudiantes/src/main/java/utn/estudiantes/modelo/Estudiante.java
> Java clase 03(video 3.1)

- Java/estudiantes/src/main/java/utn/estudiantes/repositorio/EstudianteRepositorio.java
EstudianteRepositorio = Parte 1, 2 y 3
> Java-Creación del paquete repositorio y la Interface #34

- Python/ProyectosPython/Clase01/tipo_bool.py
> Sentencia de control y booleanos

- Python/ProyectosPython/Clase01/tipo_bool.py
> Ciclos y booleanos

- JavaScript/e-commerce2022/client/js/cart.js
> Modal body

- Java/estudiantes/src/main/java/utn/estudiantes/EstudiantesApplication.java
> Comienza a trabajar el logger

- Java/estudiantes/src/main/java/utn/estudiantes/EstudiantesApplication.java
> JAVA - 4..2 Parte 1

- Python/ProyectosPython/Clase01/tipo_bool.py
PYTHON - CLASE 3 Video2 Tipo Bool
> PYTHON - CLASE 3 Video2 Tipo Bool

- Python/ProyectosPython/Clase01/tipo_bool.py
PYTHON - CLASE 3 Video 4 Colecciones
> PYTHON - CLASE 3 Video 4 Colecciones

- JavaScript/e-commerce2022/client/index.html
- JavaScript/e-commerce2022/client/js/cart.js
- JavaScript/e-commerce2022/client/js/index.js
- JavaScript/e-commerce2022/server/package.json
> Javascript video parte 1 y 2

- Pern-Stack/.gitignore
- Pern-Stack/src/app.js
> JavaScript 5.4 al 5.6

- Python/ProyectosPython/Clase01/dar_formato_str.py
Uso del método format() -> utilizamos place holder
> python -  Uso del método format() -> utilizamos place holder

- Java/.idea/misc.xml
- Java/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.form
- Java/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.java
Java - Clase 07 Parte 2 - Videos 7.5 y 7.6#105
> Java - Clase 07 Parte 2 - Videos 7.5 y 7.6#105

- Java/tienda_libros/src/main/java/utn/tienda_libros/TiendaLibrosApplication.java
- Java/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.form
- Java/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.java
8.1 Continuamos con el constructor y el método iniciarForma()
8.2 Terminando con el main
> Java - Clase 08 Parte 3 - Videos 8.1 y 8.2#114

- Java/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.java
Avanzamos con swing y la tabla -> JTable
> java- Clase 8 Update LibroFrom.java

- NodeJS/01-Hola-Mundo/entorno.js
> Actualización entorno.js

- NodeJS/02-Fundamentos_node/async/callback.js
Node Js - Clase 08 - Video 8.4 y 8.5 #117
> Creacion callback.js

- NodeJS/02-Fundamentos_node/async/callbackHell.js
NODE - Clase 09 Callback Hell
#127
> Creacion callbackHell.js

- Java/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.java
> Vm  semana 10  # 134

- Java/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.java
Java clase 10 video 5 y 6 #134
> Actualización LibroFrom.java

- NodeJS/02-Fundamentos_node/async/asyncAwait.js
> Creación asyncAwait
